fix: Allow new tag to be published after checking out a tag (#227)
Remove `git push --follow-tags` command from `actions/publish-release-tag`.

## Context

Previously the `actions/publish-release-tag` published tags using two commands:

```
git push --follow-tags && git push --tags
```

The first (`--follow-tags`) has the following behaviour:

> Push all the refs that would be pushed without this option, and also push annotated tags in refs/tags that are missing from the remote but are pointing at commit-ish that are reachable from the refs being pushed.
>
> – [git-push.txt---follow-tags](https://git-scm.com/docs/git-push#Documentation/git-push.txt---follow-tags)

The second (`--tags`) pushes all tags.

It therefore seems redundant to run `git push --follow-tags` because:
1. There's no need to push commits - deployment workflows don't create extra commits
2. There's no need to limit to annotated tags - the following `git push --tags` command overrides this

It also prevents us running the command when a pre-release tag is checked out, which is the use-case that led me to open this PR. In that case, using `--follow-tags` results in the following error:

```
Run git push --follow-tags && git push --tags
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 128.
```